baseURL: "https://rakk0o.aphorya.fr"
languageCode: "en-us"
title: "Clémence FALIGOT"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Clémence Faligot"
  description: This blog gathers the different projects I realized during my schooling but also as personnal projetcs.
  # staticPath: ""  # The path to serve the static files from
  favicon: "img/logo.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Clémence."
    subtitle: "Engineering student in computer science"
    content: "Currently in engineering school at CESI. I always have been curious and wanted to learn new skills and create things. I am looking for a rewarding experience. I like to take on challenges and give the best of myself. I always work with rigor and respect, while remaining attentive"
    image: /img/avatar.png
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/10v_JopypFMf9697MXR_sovZXYGEjhcd4/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/RaKk0o
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/clémence-faligot/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/img/avatar.png"
    content: |-
      I am a student engineer with a passion for networks in general. I am currently studying computer science, and I am very interested in the SRE profession. I am passionate about art and music, I have practiced a few years in conservatory. I also love to travel and discover new cultures and landscapes.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "C++"
        - "C#"
        - "Python"
        - "Ansible"
        - "Kubernetes"
        - "Docker"
        - "GitLab"

  # Experience
  experience:
    enable: true
    items:
      - job: "Networks and Infrastructure (Internship)"
        company: "Linguanomics RD"
        companyUrl: "https://www.linguanomics.com/"
        date: "Jan 2022 - Apr 2022"
        content: |
          Setting up a VPN, using Docker. Automating installations via Ansible and Kubernetes. Virtualization.

      - job: "User support (Internship)"
        company: "Faurecia"
        companyUrl: "http://faurecia.com/"
        date: "Apr 2021 - Jul 2021"
        content: |
          Worked in an IT team as user support, took part in internal migrations, routines, ITOPE audit preparation, Raspberry Pi configuration.
      
      - job: "Summer auxiliary"
        company: "Société générale"
        companyUrl: "https://particuliers.societegenerale.fr/"
        date: "July 2021"
        content: |
          Greeted and gave physical and telephone orientation to customers. Performed routine operations at the counter according to safety rules and instructions.

      - job: "Order picker"
        company: "Vynex"
        companyUrl: "https://www.rocket.eu/"
        date: "Sep 2020 - Dec 2021"
        content: |
          Picking and gathering of furniture hardware items in the quantity specified by the order prior to order shipment.
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Engineering diploma in Computer Science"
        school:
          name: "CESI"
          url: "https://www.cesi.fr/"
        date: "In progress since 2019"
        content: |-
          During these years I was able to realize several projects (which are detailed below), which allowed me to acquire several technical skills, but also personal. 
          Indeed, all the projects are done in group and end with a presentation, which trains us in project management and oral expression.
      - title: "High School diploma in sciences"
        school:
          name: "Collège Lycée Mabillon"
          url: "http://mabillon.net/spip/spip.php?rubrique1"
        date: "2012 - 2019"
        content: |-
          I studied a general curriculum oriented towards sciences, indeed I was in physics-chemistry speciality, and in music option. 
          During these years I was also able to participate in different clubs, including a 3D design club, where I learned to use Fusion 360.

  # Achievements
  achievements:
    enable: true
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com


  # projects
  projects:
    enable: true
    items:
      - title: System programming
        content: Realization of 3 versions of a backup software using C#.
        image: /img/projects/sysprog.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/sysprog/

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: clemence.faligot@viacesi.fr
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/RaKk0o
      linkedin: https://www.linkedin.com/in/clémence-faligot/