baseURL: "https://rakk0o.aphorya.fr"
languageCode: "en-us"
title: "Clémence FALIGOT"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1


params:
  socialShare: false

  title: "Clémence Faligot"
  description: This blog gathers the different projects I realized during my schooling but also as personnal projetcs.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/img/logo.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Clémence."
    subtitle: "Engineering student in computer science"
    content: "Currently in engineering school at CESI. I always have been curious and wanted to learn new skills and create things. I am looking for a rewarding experience. I like to take on challenges and give the best of myself. I always work with rigor and respect, while remaining attentive"
    image: "/img/avatar.png"
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/10v_JopypFMf9697MXR_sovZXYGEjhcd4/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/RaKk0o
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/clémence-faligot/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/img/avatar.png"
    content: |-
      I am a student engineer with a passion for networks in general. I am currently studying computer science, and I am very interested in the SRE profession. I am passionate about art and music, I have practiced a few years in conservatory. I also love to travel and discover new cultures and landscapes.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "C++"
        - "C#"
        - "Python"
        - "Ansible"
        - "Kubernetes"
        - "Docker"
        - "GitLab"

  # Experience
  experience:
    enable: true
    items:
      - job: "Networks and Infrastructure (Internship)"
        company: "Linguanomics RD"
        companyUrl: "https://www.linguanomics.com/"
        date: "Jan 2022 - Apr 2022"
        content: |
          Setting up a VPN, using Docker. Automating installations via Ansible and Kubernetes. Virtualization.
        featuredLink:
          enable: true
          name: "Letter of appreciation (fr)"
          url: "https://drive.google.com/file/d/1of4V3SsI3ZlIMb_W6Yv9B1Wo5f7FJGfj/view?usp=sharing"

      - job: "User support (Internship)"
        company: "Faurecia"
        companyUrl: "http://faurecia.com/"
        date: "Apr 2021 - Jul 2021"
        content: |
          Worked in an IT team as user support, took part in internal migrations, routines, ITOPE audit preparation, Raspberry Pi configuration.
      
      - job: "Summer auxiliary"
        company: "Société générale"
        companyUrl: "https://particuliers.societegenerale.fr/"
        date: "July 2021"
        content: |
          Greeted and gave physical and telephone orientation to customers. Performed routine operations at the counter according to safety rules and instructions.

      - job: "Order picker"
        company: "Vynex"
        companyUrl: "https://www.rocket.eu/"
        date: "Sep 2020 - Dec 2021"
        content: |
          Picking and gathering of furniture hardware items in the quantity specified by the order prior to order shipment.
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Engineering diploma in Computer Science"
        school:
          name: "CESI"
          url: "https://ecole-ingenieurs.cesi.fr/en/"
        date: "In progress since 2019"
        content: |-
          During these years I was able to realize several projects (which are detailed below), which allowed me to acquire several technical skills, but also personal. 
          Indeed, all the projects are done in group and end with a presentation, which trains us in project management and oral expression.
      - title: "High School diploma in sciences"
        school:
          name: "Collège Lycée Mabillon"
          url: "http://mabillon.net/spip/spip.php?rubrique1"
        date: "2012 - 2019"
        content: |-
          I studied a general curriculum oriented towards sciences, indeed I was in physics-chemistry speciality, and in music option. 
          During these years I was also able to participate in different clubs, including a 3D design club, where I learned to use Fusion 360.

  # Achievements
  achievements:
    enable: true
    items:
      - title: Cisco CCNA1
        content: Obtained on 05/02/2021.
        url: https://drive.google.com/file/d/1vcvTn1GfK8FJ6660m45GcfArKIjkxuOn/view?usp=sharing
      
      - title: BIA
        content: Aeronautical initiation certificate.
        # url: 

      - title: Driving licence
        # content: 
        # url: 

  # projects
  projects:
    enable: true
    items:
      - title: System programming
        content: Realization of 3 versions of a backup software using C#.
        image: /img/projects/sysprog.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/sysprog/
      
      - title: Information system
        content: Administration of an I.S. using PowerShell, Firewall, VPN,...
        image: /img/projects/isystem.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/isystem/
                
      - title: Web development
        content: Creation of LinkedIn type website using HTML, CSS, PHP, JS.
        image: /img/projects/webdev.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/webdev/
                
      - title: Network
        content: Configuration of networks via Packet Tracer using CISCO.
        image: /img/projects/network.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/network/
                
      - title: Object-oriented programming
        content: Realization of a management application using C++.
        image: /img/projects/oop.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/oop/
                
      - title: Embedded system
        content: Realization of a weather station using Arduino.
        image: /img/projects/embeddedsystem.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/embeddedsystem/
                          
      - title: Industry
        content: Study of the conception to the production of a product.
        image: /img/projects/industry.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/industry/
                          
      - title: Data Base
        content: Creation, management, and queries in the database using MySQL.
        image: /img/projects/database.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/database/
                          
      - title: Signal
        content: Realization of communication programs using Python.
        image: /img/projects/signal.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/signal/
                          
      - title: Electronics
        content: Realization of a security system using Arduino.
        image: /img/projects/electronics.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/electronics/

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: clemence.faligot@viacesi.fr
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/RaKk0o
      linkedin: https://www.linkedin.com/in/clémence-faligot/